version: "3"

vars:
  PROJ_NAME: iris-graal
  PROJ_VER: 1.0.0

tasks:
  buildImage:
    cmds:
      - mvn -Pnative native:compile
      - docker build -t {.PROJ_NAME}:{.PROJ_VER} .
      # - docker push {.PROJ_NAME}:{.PROJ_VER}
