version: "3"

dotenv:
  - ".env"

tasks:
  buildJar:
    cmds:
      - mvn clean package -DskipTests -Drevision="$VERSION-SNAPSHOT"
  native:
    cmds:
      - mvn -Pnative native:compile -DskipTests
  buildImage:
    cmds:
      - task: native
      - docker build -t "$APP:$VERSION" .
      # - docker push "$APP:$VERSION"
  jib:
    cmds:
      - echo "$AUTHOR/$APP:$VERSION"
      # - mvn compile jib:build -Dimage="$AUTHOR/$APP:$VERSION"
